version: '3'
services:
  serviceregistry:
    image: 'durgaprasad707/serviceregistry:0.0.1'
    container_name: 'serviceregistry'
    ports: 
      - '8761:8761'
  configserver:
    image: 'durgaprasad707/configserver:0.0.1'
    container_name: 'configserver'
    ports:
      - '9296:9296'
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
    healthcheck:
      test: ["CMD", "CURL", "-f" "http://configserver:9296/actuator/healthchek" ]
      interval: 10s
      timeout: 5s  
      retries: 5  
    depends_on:
      - serviceregistry
  cloudgateway:
    image: 'durgaprasad707/cloudgateway:0.0.1'
    container_name: 'cloudgateway'
    ports:
      - '9090'
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
      - Config_Server_URL=configserver
    depends_on:
      - configserver:
          codition: service_healthy
     
