version: '3'
services:
  serviceregistry:
    image: 'durgaprasad707/serviceregistry:0.0.1'
    container_name: 'serviceregistry'
    ports: 
      - '8761:8761'
  configserver:
    image: 'durgaprasad707/configserver:0.0.1'
    container_name: 'configserver'
    ports:
      - '9296:9296'
    environment:
      - EUREKA_SERVER_ADDRESS= http://host.docker.internal:8761/eureka
    depends_on:
      - serviceregistry
  cloudgateway:
    image: 'durgaprasad707/cloudgateway:0.0.1'
    container_name: 'cloudgateway'
    ports:
      - '9090'
    environment:
      - EUREKA_SERVER_ADDRESS= http://host.docker.internal:8761/eureka
      - Config_Server_URL= configserver
    depends_on:
      - configserver 
    
     
